name: Build Main
on:
  push:
    branches:
      - main

jobs:
  build-ubuntu:
    name: build & tests on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build & Test
        run: |
          chmod +x ./build.sh
          ./build.sh Tests
  
  build-macos:
    name: build & tests on Ubuntu
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build & Test
        run: |
          chmod +x ./build.sh
          ./build.sh Tests
  
  build-windows:
    name: build & tests on Ubuntu
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build & Test
        run: |
          ./build.ps1 Tests
  
  pack:
    name: build & tests on Ubuntu
    needs:
      - build-ubuntu
      - build-macos
      - build-windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build, Test, Publish & Create Release
        run: |
          chmod +x ./build.sh
          ./build.sh Publish CreateRelease --api-key ${{secrets.NUGET_TOKEN}}

      - uses: actions/upload-artifact@v3
        with:
          name: packages
          path: artifacts/packages